// src/Web.React/ClientApp/src/components/AddProduct.js
import React, {Component} from 'react';

export class AddProduct extends Component {

    constructor(props) {
        super(props);
        this.state = {
            title: "",
            description: "",
            seller: "",
            price: 0,
            quantity: 0,
        };

        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(event) {

        const target = event.target;
        const value = target.value;
        const name = target.name;

        this.setState({
            [name]: value 
        });
    }

    handleSubmit(event) {
        alert('New product created: ' + this.state.title);
        event.preventDefault();
        console.log(this.state);
    }

    render() {
        return (
            <div>
                <h1>Add a Product</h1>
                <form onSubmit={this.handleSubmit}>

                    <div>
                        <p>Product Title: <input name="title" type="text" value={this.state.title} onChange={this.handleChange} /></p>
                    </div>
    
                    <div>
                        <p>Price: £<input name="price" type="number" value={this.state.price} onChange={this.handleChange} /></p>
                    </div>

                    <div>
                        <p>Quantity: <input name="quantity" type="number" value={this.state.quantity} onChange={this.handleChange} /></p>
                    </div>

                    <div>
                        <p>Description: <input name="description" type="text" value={this.state.description} onChange={this.handleChange} /></p>
                    </div>

                    <div>
                        <p>Seller's Name: <input name="seller" type="text" value={this.state.seller} onChange={this.handleChange} /></p>
                    </div>

                    <input type="submit" value="Submit" />

                </form>
            </div>
        );
    }
}

// Ganges/ClientApp/src/app/add-product/add-product.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { Product } from '../product'

@Component({
  selector: 'app-add-product',
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.css']
})
export class AddProductComponent implements OnInit {

  //https://angular.io/guide/reactive-forms
  productForm = new FormGroup({
    title: new FormControl(''),
    description: new FormControl(''),
    seller: new FormControl(''),
    price: new FormControl(''),
    quantity: new FormControl(''),
    imageUrl: new FormControl(''),
  });

  constructor() { }

  ngOnInit() {
  }

  onSubmit() {
    // Create a product object from the values in the form
    var product: Product = {
      id: 0,
      title: this.productForm.value.title,
      description: this.productForm.value.description,
      seller: this.productForm.value.seller,
      price: this.productForm.value.price,
      quantity: this.productForm.value.quantity,
      imageUrl: this.productForm.value.imageUrl
    }
    console.log(product);
  }

}

<h1>Add a Product!</h1>
<form [formGroup]="productForm" (ngSubmit)="onSubmit()">

    <div>
        Product Title:
        <input type="text" formControlName="title">
    </div>
    
    <div>
        Description:
        <input type="text" formControlName="description">
    </div>

    <div>
        Seller:
        <input type="text" formControlName="seller">
    </div>

    <div>
        Price:
        <input type="text" formControlName="price">
    </div>

    <div>
        Quantity:
        <input type="text" formControlName="quantity">
    </div>

    <div>
        ImageUrl:
        <input type="text" formControlName="imageUrl">
    </div>

    <button type="submit" [disabled]="!productForm.valid">Submit</button>

</form>
