// src/Web.Angular/ClientApp/src/app/components/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService } from '../../services/product.service';
import { Observable } from 'rxjs';
import { Product } from '../../product';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss']
})
export class ProductsComponent implements OnInit {

  public products$: Observable<Product[]>;

  public constructor(private productService: ProductService) {}

  public ngOnInit(): void {
    this.products$ = this.productService.getAllProducts();
  }

}
<h1>Products</h1>

<a routerLink="/add-product"><p>Add a product</p></a>

<div *ngIf="(products$ | async) as products; else loading">
    <ul>
        <li *ngFor="let product of products">
            <div>
                <a routerLink="/products/{{product.productId}}"><img src="assets/{{product.imageUrl}}"/></a>
            </div>
            <div>
                <p id="productTitle"><a routerLink="/products/{{product.productId}}">{{ product.title }}</a></p>
                <p id="productSeller">Seller: {{ product.seller }}</p>
                <p id="productPrice"><a routerLink="/products/{{product.productId}}">£{{ product.price }}</a></p>
                <p id="productDelivery">FREE Delivery</p>
            </div>
        </li>
    </ul>
</div>

<ng-template #loading>
    Loading...
</ng-template>

// src/Web.React/ClientApp/src/components/Products.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

import './Products.css';

export class Products extends Component {
  static displayName = Products.name;

  constructor(props) {
    super(props);
    this.state = { products: [], loading: true };
  }

  componentDidMount() {
    this.populateProductsData();
  }

  async populateProductsData() {
    const response = await fetch('api/products');
    const data = await response.json();
    this.setState({ products: data, loading: false });
  }

  render() {
    return (
      <div>
        <h1 id="tabelLabel" >Products</h1>
        <Link to={"add-product"}><p>Add a product</p></Link>
        {this.renderProducts()}
      </div>
    );
  }

  renderProducts() {
    if(this.state.loading) {
      return <p><em>Loading...</em></p>
    }
    else {
      return (
        <div id="products">
          <ul>
            {this.state.products.map(product =>
              <li>
                <div>
                  <Link to={"product/" + product.productId}>
                    <img src={"images/" + product.imageUrl} alt=""/>
                  </Link>
                </div>
                <div>             
                  <p id="productTitle"><Link to={"product/" + product.productId}>{ product.title }</Link></p>
                  <p id="productSeller">Seller: { product.seller }</p>
                  <p id="productPrice"><Link to={"product/" + product.productId}>£{ product.price }</Link></p>
                  <p id="productDelivery">FREE Delivery</p>
              </div>
              </li>
            )}
          </ul>
        </div>
      );
    }
  }
}
