// src/Web.Angular/ClientApp/src/app/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService } from '../product.service';
import { Observable } from 'rxjs';
import { Product } from '../product';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss']
})
export class ProductsComponent implements OnInit {

  products$: Observable<Product[]>;

  constructor(private productService: ProductService) {}

  ngOnInit() {
    this.products$ = this.productService.getProducts();
  }

}
<h1>Products</h1>

<p>The product data shown here is fetched from the server.</p>


<div *ngIf="(products$ | async) as products;">

    <ul>
        <li *ngFor="let product of products">
            <div>
                <a routerLink="/products/{{product.id}}"><img src="assets/{{product.imageUrl}}"/></a>
            </div>
            <div>
                <p id="productTitle"><a routerLink="/products/{{product.id}}">{{ product.title }}</a></p>
                <p id="productSeller">Seller: {{ product.seller }}</p>
                <p id="productPrice"><a routerLink="/products/{{product.id}}">{{ product.price | currency }}</a></p>
                <p id="productDelivery">FREE Delivery</p>
            </div>
        </li>
    </ul>

</div>

// src/Web.React/ClientApp/src/components/Products.js
import React, { Component } from 'react';
import './Products.css';

export class Products extends Component {
  static displayName = Products.name;

  constructor(props) {
    super(props);
    this.state = { products: [], loading: true };
  }

  componentDidMount() {
    this.populateProductsData();
  }

  static renderProductsTable(products) {
    return (
      <div id="products">
        <ul>
          {products.map(product =>
            <li>
              <div>
                <img src="assets/{product.imageUrl}" alt=""/>
              </div>
              <div>
                <p id="productTitle">{ product.title }</p>
                <p id="productSeller">Seller: { product.seller }</p>
                <p id="productPrice">£{ product.price }</p>
                <p id="productDelivery">FREE Delivery</p>
            </div>
            </li>
          )}
        </ul>
      </div>
    );
  }

  render() {
    let contents = this.state.loading
      ? <p><em>Loading...</em></p>
      : Products.renderProductsTable(this.state.products);

    return (
      <div>
        <h1 id="tabelLabel" >Products</h1>
        <p>This component demonstrates fetching data from the server.</p>
        {contents}
      </div>
    );
  }

  async populateProductsData() {
    const response = await fetch('api/products');
    const data = await response.json();
    this.setState({ products: data, loading: false });
  }
}
